#lang racket
(define (for1 row now)
  (if(> now row)
     (void)
     (begin (display now) (display ",") (for1 row (+ 1 now)))))
(define (for2 line row now)
  (if(> now line)
     (void)
     (begin (for1 row 1) (newline) (for2 line row (+ 1 now)))))
(define (loop)
  (define line (read))
  (define row (read))
  (if(equal? line eof)
     (void)
     (begin (for2 line row 1) (loop))))
(loop)