#lang racket
(define (for idx end fun)
  (if (= idx end)
      (void)
      (begin (fun idx)
             (for (+ 1 idx) end fun))))

(define (reverse lst)
  (define vec (list->vector lst))
  (define ret (vector))
  (begin (for 0 (vector-length vec)
           (lambda (idx)
             (set! ret (vector-append (vector (vector-ref vec idx)) ret)))
           )
         (vector->list ret)
         )
  )

(define (deep-reverse lst)
  (define vec (list->vector lst))
  (begin (set! vec (list->vector (reverse lst)))
         (for 0 (vector-length vec)
           (lambda (idx)
             (if (list? (vector-ref vec idx))
                 (vector-set! vec idx (deep-reverse (vector-ref vec idx)))
                 (void)))
           )
         (vector->list vec)
         )
  )

(define (work)
  (let ((l (read)))
    (if (eq? l eof)
        (void)
        (begin (displayln (deep-reverse l))
               (work)))
    )
  )

(work)